### ISSUE TITLE
Section Request: Legal

### ISSUE THREAD

**Issue by danijeljw-RPC** [repasscloud/repasscloud.com#30]
Section Request: Legal

```yaml
---
layout: default
title: "Legal"
permalink: /legal/
---

{% include section/legal.html %}
```

_Originally posted by @danijeljw-RPC in https://github.com/repasscloud/repasscloud.com/issues/6#issuecomment-835824471_
