### ISSUE TITLE
Section Request: File a Support Ticket

### ISSUE THREAD

**Issue by danijeljw-RPC** [repasscloud/repasscloud.com#32]
Section Request: File a Support Ticket

```yaml
---
layout: default
title: "Support"
permalink: /support/
---

{% include section/support.html %}
```

_Originally posted by @danijeljw-RPC in https://github.com/repasscloud/repasscloud.com/issues/6#issuecomment-835824661_
